import type { Metadata } from "next";
"eslint-disable-next-line";
import Link from "next/link";
import  Navbar  from "./components/Navbar/index";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
      <div style={{height: "100px", background: "red"}}>
        <div>
        <Link href="/dashboard/portfolio">Portfolio</Link>
        <Link href="/dashboard/analytics">Analytics</Link>
        <Link href="/">Home</Link>
        </div>
      <div>
    <Navbar/>
      </div>
      </div>
        {children}
      </body>
    </html>
  );
}
