
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

import  Navbar  from './components/Navbar/index';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div style={{height: '100px', background: 'red'}}>

        <div>
        <Link href="/dashboard/portfolio">Portfolio</Link>
        <Link href="/dashboard/analytics">Analytics</Link>
        <Link href="/dashboard/settings/profile">Profile</Link>
        <Link href="/dashboard/settings/password">Password</Link>
        </div>

      <div>
    <Navbar/>
      </div>

      </div>
        {children}
      </body>
    </html>
  );
}
